### ISSUE TITLE
Can not create gear using 2.5.0

### ISSUE THREAD

**Issue by matthewsurfshack** [tyrcho/openshift-cartridge-play2#23]
I'm attempting to setup a new gear with Play 2.5.0. Following the instructions, when I go to the openshift web interface I put in the following URL for the cartridge:
http://cartreflect-claytondev.rhcloud.com/reflect?github=tyrcho/openshift-cartridge-play2&commit=play-2.5.0

The application never starts up. When I check the runtime/repo directory it is empty. When I attempt to clone the repository to my local machine I receive this: fatal: protocol error: 
bad line length character: Inva

I deployed a second application using 
http://cartreflect-claytondev.rhcloud.com/reflect?github=tyrcho/openshift-cartridge-play2&commit=play-2.3.0
and everything worked as expected, the repo directory had a the default play project in it.

I've tried deploying 2.5.0 three times now and each time gives me the same result.

**Comment by tyrcho** [comment]
@fpirola would you have a look ? I just gave you push rights to the repository so you can fix issues without waiting for my go to merge the pull requests.

**Comment by fpirola** [comment]
Hi @matthewsurfshack,
I made some check and I found a temporary patch.
When you create a cartridge via openshift interface by "Code Anything" (URL of a cartridge) you must fill in step 2 - "Configure the application" the field "Source Code" with "https://github.com/tyrcho/openshift-cartridge-play2.git".

I will investigate on this error

**Comment by matthewsurfshack** [comment]
@fpirola Still no luck. This time it created the repository correctly but the application won't start. When I try to manually start it with `gear start` it gives me the output:
CLIENT_RESULT: Application is either stopped or inaccessible

**Comment by fpirola** [comment]
@matthewsurfshack I tried now and it works for me (see https://testissues23-pirola.rhcloud.com/).
Try with these steps:
  1. Go to https://openshift.redhat.com/app/console/applications
  2. Click on "Add Application…"
  3. Go to the bottom page and in Code Anything "URL to a cartridge definition" insert:
`http://cartreflect-claytondev.rhcloud.com/reflect?github=tyrcho/openshift-cartridge-play2&commit=play-2.5.0`
  4. Click on "Next"
  5. Define an url for the Application Name
  6. In "Source Code" field insert "https://github.com/tyrcho/openshift-cartridge-play2.git"
  7. Go to the bottom page and click the button "Create Application"
  8. Wait ~15 minutes for the first build. It takes a while because it downloads activator and its dependecies
  9. Connect via ssh
  10. Wait until the application is stopped (via 'gear status') 
  11. Execute 'gear build'
  12. Execute 'gear start'

Let me know
Best Regards

**Comment by fpirola** [comment]
@matthewsurfshack I fixed this issue and updated README file
Thank you for your feedback

Best Regards
