### ISSUE TITLE
properties deprecated in config file and start command  

### ISSUE THREAD

**Issue by almothafar** [tyrcho/openshift-cartridge-play2#28]
Hi, 

I just have note about deprecated properties in config file and start up command, i'm not sure why they are not updated, since some deprecated from 2.4 , and i'm working with 2.5 now, examples not all :
- `play.i18n.langs = "en"`  should be `play.i18n.langs = ["en"]`
- `# evolutionplugin=disabled` should be `# play.evolutions.enabled=true`
- `application.secret` should be `play.crypto.secret`

in command: 
- `-DapplyEvolutions.default=true` should be `-Dplay.evolutions.db.default.autoApply=true` 

I understand that you want to cover all versions from 2.x to 2.5 but maybe good idea to have some conditions maybe to load specific template or maybe provide legacy cartridge and bleeding edge cartridge?

Its sound like deprecation not hurt, but actually in play framework, **it is**, like language properties, i understand that I can replace them with my own, but I just want to give my feedback and suggestions anyway.

**Comment by fpirola** [comment]
Hi @almothafar ,
at the moment I am writing this comment, the  config file properties comes with the current default play-scala template. For this reason I will not change config file.
I will not update the command `-DapplyEvolutions.default=true`  in order to cover old versions.

Thank you for your feedback and sorry for the late response,
Best regards
